"""create stock transfer tables

Revision ID: 25e5955b73d2
Revises: 0c64076151b4
Create Date: 2026-08-07 11:09:36.090898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e5955b73d2'
down_revision: Union[str, Sequence[str], None] = '0c64076151b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_number', sa.String(length=30), nullable=False),
    sa.Column('source_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('destination_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'IN_TRANSIT', 'RECEIVED', 'REJECTED', name='transferstatus'), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_number')
    )
    op.create_table('stock_transfer_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_transfer_items')
    op.drop_table('stock_transfers')
    # ### end Alembic commands ###
