"""create inventory alerts table

Revision ID: 478d3995b655
Revises: 25e5955b73d2
Create Date: 2026-08-07 11:30:00.279444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478d3995b655'
down_revision: Union[str, Sequence[str], None] = '25e5955b73d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('current_quantity', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('LOW_STOCK', 'OUT_OF_STOCK', 'OVER_STOCK', 'EXPIRED_PRODUCT', name='alerttype'), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_alerts')
    # ### end Alembic commands ###
