"""add received quantity to purchase order items

Revision ID: 8b36cc23459b
Revises: 478d3995b655
Create Date: 2026-08-10 08:44:43.215796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b36cc23459b'
down_revision: Union[str, Sequence[str], None] = '478d3995b655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "purchase_order_items",
        sa.Column(
            "received_quantity",
            sa.Integer(),
            nullable=False,
            server_default="0"
        )
    )    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_items', 'received_quantity')
    # ### end Alembic commands ###
