"""add batch and expiry date to inventory

Revision ID: ca5f726afa22
Revises: 8b36cc23459b
Create Date: 2026-08-10 10:17:10.344334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5f726afa22'
down_revision: Union[str, Sequence[str], None] = '8b36cc23459b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('batch_number', sa.String(length=100), nullable=True))
    op.add_column('inventory', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_inventory_batch_number'), 'inventory', ['batch_number'], unique=False)
    op.create_index(op.f('ix_inventory_expiry_date'), 'inventory', ['expiry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_expiry_date'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_batch_number'), table_name='inventory')
    op.drop_column('inventory', 'expiry_date')
    op.drop_column('inventory', 'batch_number')
    # ### end Alembic commands ###
